// import { v4 as uuidv4 } from "uuid";

function foodData() {
  return [
    {
      name: "Bahroma",
      search_names: ["бахрома", "bahroma"],
      id: 0,
      city: "Санкт-Петербург",
      address: {
        link: "https://go.2gis.com/g913z",
        text: "П.С. пр. Большой 30",
      },
      metro: {
        name: "Чкаловская",
        icon:
          "https://upload.wikimedia.org/wikipedia/commons/a/af/Spb_metro_line5.svg",
      },
      description:
        "Восточный ресторан сети с акцентом на узбекскую кухню. В меню заведения входят хиты узбекской кухни вроде плова и мантов, а также кавказские позиции, включая блюда на мангале, плюс раздел с блюдами европейской кухни. В барной карте представлены как доступные, так и дорогие вина разных регионов, есть стандартный набор коктейлей и выпивки. В заведении регулярно проходят вечера живой музыки. В ресторане действует доставка.",
      images: [
        "https://www.restoclub.ru/uploads/place_thumbnail_big/0/5/0/c/050c050a8932759770fe696990863fbc.jpg",
        "https://www.restoclub.ru/uploads/place_thumbnail_big/1/4/9/a/149af2c2dd28b749271d22257fd4bf1a.jpg",
      ],
      rating: null,
      average_price: 1000,
      phone_number: {
        link: "6127556",
        text: "612-75-56",
      },
      kitchen: [
        "европейская",
        "грузинская",
        "узбекская",
        "армянская",
        "восточная",
      ],
      menu: [
        {
          id: "0d1",
          restaurant: 0,
          name: "Люля-кебаб из цыпленка",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "150/80/30",
          nutritional_value: {
            size: "на одну порцию",
            fats: 39.0,
            prots: 43.0,
            carbs: 42.0,
            kcal: 691,
          },
          price: 210,
          composition:
            "Кура бедро, говядина, кориандр молотый, соль, перец, бараний жир / морковь, сахар, масло растительное, уксус столовоый, перец кайенский молотый, зелень, паприка молотая, свекла, чеснок, капуста, б/к, лавровый лист, стебель сельдерея, лук репчатый, уксус, сумах / томатная паста, чеснок, сахар, уцхо сунели, перец чили, зелень кинзы",
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "0d2",
          restaurant: 0,
          name: "Шашлык из бедра цыпленка",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "170/60/60/20/40/30",
          nutritional_value: {
            size: "на одну порцию",
            fats: 40.0,
            prots: 54.5,
            carbs: 43.4,
            kcal: 752,
          },
          price: 230,
          composition:
            "Кура филе бедра, майонез, чеснок, уксус, соус соевый, соль, перец черный / помидоры, огурцы, лук репчатый, уксус, сумах / лаваш армянский / томатная паста, чеснок, сахар, уцхо сунели, перец чили, зелень кинзы",
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "0d3",
          restaurant: 0,
          name: "Шашлык из грудки цыпленка",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "180/60/60/20/40/30",
          nutritional_value: {
            size: "на одну порцию",
            fats: 35.0,
            prots: 50.5,
            carbs: 33.4,
            kcal: 647,
          },
          price: 240,
          composition:
            "Кура филе грудки, майонез, чеснок, соус соевый, соль, перец черный / помидоры, огурцы, лук репчатый, уксус, сумах / лаваш армянский / томатная паста, чеснок, сахар, уцхо сунели, перец чили, зелень кинзы",
          inBasket: false,
          isFavorite: false,
        },
      ],
    },
    {
      name: "Frank",
      search_names: ["франк", "frank"],
      id: 1,
      city: "Санкт-Петербург",
      address: {
        link: "https://go.2gis.com/yypey",
        text: "Московский проспект, 175",
      },
      metro: {
        name: "Московская",
        icon:
          "https://upload.wikimedia.org/wikipedia/commons/7/73/Spb_metro_line2.svg",
      },
      description:
        "Стритфуд-бар на Московском проспекте для поклонников ребрышек. В заведении организовали стеклянный бар с подсветкой и мониторами, обеденный зал с открытой кухней, зону с диванчиками и детскую комнату. Стены расписаны яркими мультяшными изображениями. Главное блюдо здесь — ребрышки: говяжьи, бараньи или свиные, с различными соусами. Есть стейки, бургеры и шаверма. В барной карте акцент сделан на пиво и коктейли.",
      images: [
        "https://www.restoclub.ru/uploads/place_thumbnail_big/c/6/a/8/c6a8728e2314cca03dbddc2840b18b97.jpg",
        "https://www.restoclub.ru/uploads/place_thumbnail_big/4/3/8/1/438116b782c9eeffbf7490ba44e6ec78.jpg",
        "https://www.restoclub.ru/uploads/place_thumbnail_big/3/0/8/3/30838a6c2ca2fbe4d1a531003fb08ce0.jpg",
        "https://www.restoclub.ru/uploads/place_thumbnail_big/c/2/c/d/c2cd857a3f58f5a7368f5d16b22fe38f.jpg",
        "https://www.restoclub.ru/uploads/place_thumbnail_big/1/7/a/7/17a7b0a5e98ce32052db4f6e1e2f9123.jpg",
      ],
      rating: null,
      average_price: 1400,
      phone_number: {
        link: "2007300",
        text: "200-73-00",
      },
      kitchen: ["американская", "стритфуд", "смешанная"],
      menu: [
        {
          id: "1d1",
          restaurant: 1,
          name: "Начос из гуакомоле и красной фасолью",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "180",
          nutritional_value: {
            size: "на одну порцию",
            fats: 3.59,
            prots: 7.76,
            carbs: 72.45,
            kcal: 352.93,
          },
          price: 260,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d2",
          restaurant: 1,
          name: "Тако с говядиной",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "294",
          nutritional_value: {
            size: "на одну порцию",
            fats: 23.56,
            prots: 26.95,
            carbs: 31.28,
            kcal: 444.99,
          },
          price: 420,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d3",
          restaurant: 1,
          name: "Тартар из говядины",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "200",
          nutritional_value: {
            size: "на одну порцию",
            fats: 25.88,
            prots: 26.76,
            carbs: 4.35,
            kcal: 257.36,
          },
          price: 480,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d4",
          restaurant: 1,
          name: "Крылья сырные",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "383",
          nutritional_value: {
            size: "на одну порцию",
            fats: 62.25,
            prots: 66.5,
            carbs: 7.63,
            kcal: 856.77,
          },
          price: 460,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d5",
          restaurant: 1,
          name: "Крылья сладкая Coca-cola",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "541",
          nutritional_value: {
            size: "на одну порцию",
            fats: 54.94,
            prots: 76.23,
            carbs: 28.89,
            kcal: 914.98,
          },
          price: 460,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d6",
          restaurant: 1,
          name: "Японские крылья",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "490",
          nutritional_value: {
            size: "на одну порцию",
            fats: 50.25,
            prots: 71.97,
            carbs: 24.24,
            kcal: 837.09,
          },
          price: 460,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d7",
          restaurant: 1,
          name: "Мексиканские крылья",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "500",
          nutritional_value: {
            size: "на одну порцию",
            fats: 49.55,
            prots: 71.85,
            carbs: 35.35,
            kcal: 874.75,
          },
          price: 460,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d8",
          restaurant: 1,
          name: "Жаренные креветки с хрустящей чиабаттой",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "282",
          nutritional_value: {
            size: "на одну порцию",
            fats: 13.32,
            prots: 47.82,
            carbs: 29.86,
            kcal: 430.58,
          },
          price: 690,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d9",
          restaurant: 1,
          name: "Картофель фри с пармезаном и трюфельным маслом",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "269.5",
          nutritional_value: {
            size: "на одну порцию",
            fats: 50.63,
            prots: 11.6,
            carbs: 14.6,
            kcal: 560.4,
          },
          price: 350,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d10",
          restaurant: 1,
          name: "Овощные палочки с соусом тар-тар",
          category: {
            number: 0,
            name: "горячие и холодные закуски",
          },
          weight: "270",
          nutritional_value: {
            size: "на одну порцию",
            fats: 17.03,
            prots: 4.82,
            carbs: 11.76,
            kcal: 219.59,
          },
          price: 250,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d11",
          restaurant: 1,
          name: "Картофельный с реберным мясом",
          category: {
            number: 3,
            name: "салаты",
          },
          weight: "140",
          nutritional_value: {
            size: "на одну порцию",
            fats: 35.39,
            prots: 16.92,
            carbs: 40.0,
            kcal: 546.12,
          },
          price: 350,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d12",
          restaurant: 1,
          name: "Калифорнийский с киноа, авокадо и креветками",
          category: {
            number: 3,
            name: "салаты",
          },
          weight: "351",
          nutritional_value: {
            size: "на одну порцию",
            fats: 90.45,
            prots: 33.88,
            carbs: 25.83,
            kcal: 1052.98,
          },
          price: 590,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d13",
          restaurant: 1,
          name: "С куриной грудкой на гриле",
          category: {
            number: 3,
            name: "салаты",
          },
          weight: "265",
          nutritional_value: {
            size: "на одну порцию",
            fats: 16.4,
            prots: 36.96,
            carbs: 15.31,
            kcal: 356.73,
          },
          price: 480,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d14",
          restaurant: 1,
          name: "С хрустящими баклажанами и бакинскими томатами",
          category: {
            number: 3,
            name: "салаты",
          },
          weight: "156",
          nutritional_value: {
            size: "на одну порцию",
            fats: 7.51,
            prots: 14.38,
            carbs: 21.89,
            kcal: 212.67,
          },
          price: 450,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d15",
          restaurant: 1,
          name: "Салат с креветками и черри",
          category: {
            number: 3,
            name: "салаты",
          },
          weight: "281",
          nutritional_value: {
            size: "на одну порцию",
            fats: 20.97,
            prots: 30.04,
            carbs: 10.45,
            kcal: 350.74,
          },
          price: 550,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d16",
          restaurant: 1,
          name: "Овощной микс-салат",
          category: {
            number: 3,
            name: "салаты",
          },
          weight: "291",
          nutritional_value: {
            size: "на одну порцию",
            fats: 10.6,
            prots: 3.3,
            carbs: 11.6,
            kcal: 155.0,
          },
          price: 380,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d17",
          restaurant: 1,
          name: "Куриный бульон",
          category: {
            number: 4,
            name: "супы",
          },
          weight: "337",
          nutritional_value: {
            size: "на одну порцию",
            fats: 17.71,
            prots: 36.15,
            carbs: 15.0,
            kcal: 363.97,
          },
          price: 290,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d18",
          restaurant: 1,
          name: "Томатный с креветками",
          category: {
            number: 4,
            name: "супы",
          },
          weight: "347",
          nutritional_value: {
            size: "на одну порцию",
            fats: 7.12,
            prots: 20.85,
            carbs: 15.64,
            kcal: 210.1,
          },
          price: 350,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d19",
          restaurant: 1,
          name: "Сырный с беконом",
          category: {
            number: 4,
            name: "супы",
          },
          weight: "310",
          nutritional_value: {
            size: "на одну порцию",
            fats: 59.95,
            prots: 45.69,
            carbs: 21.22,
            kcal: 807.19,
          },
          price: 380,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d20",
          restaurant: 1,
          name: "Суп-гуляш",
          category: {
            number: 4,
            name: "супы",
          },
          weight: "281",
          nutritional_value: {
            size: "на одну порцию",
            fats: 7.2,
            prots: 28.3,
            carbs: 31.56,
            kcal: 304.21,
          },
          price: 420,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d21",
          restaurant: 1,
          name: "Medium size ребра свинные",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "250",
          nutritional_value: {
            size: "на одну порцию",
            fats: 67.56,
            prots: 34.07,
            carbs: 1.61,
            kcal: 750.7,
          },
          price: 470,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d22",
          restaurant: 1,
          name: "Big size ребра свинные",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "450",
          nutritional_value: {
            size: "на одну порцию",
            fats: 121.6,
            prots: 61.33,
            carbs: 2.89,
            kcal: 1351.26,
          },
          price: 590,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d23",
          restaurant: 1,
          name: "Ассорти из свинных ребер в трех соусах",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "730",
          nutritional_value: {
            size: "на одну порцию",
            fats: 136.1,
            prots: 74.74,
            carbs: 68.66,
            kcal: 1798.42,
          },
          price: 750,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d24",
          restaurant: 1,
          name: "Мраморное говяжье ребро",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "500",
          nutritional_value: {
            size: "на одну порцию",
            fats: 100.89,
            prots: 72.54,
            carbs: 2.7,
            kcal: 1208.97,
          },
          price: 990,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d25",
          restaurant: 1,
          name: "Ребра свинные King Size Extra Hot с начос",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "1048",
          nutritional_value: {
            size: "на одну порцию",
            fats: 199.91,
            prots: 103.34,
            carbs: 108.27,
            kcal: 2645.61,
          },
          price: 1290,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d26",
          restaurant: 1,
          name: "Ребра свинные King Size с бадьяном рибс",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "1005",
          nutritional_value: {
            size: "на одну порцию",
            fats: 171.86,
            prots: 96.96,
            carbs: 63.07,
            kcal: 2186.79,
          },
          price: 1290,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d27",
          restaurant: 1,
          name: "Ребра свинные King Size с пепперони и моцареллой",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "1182",
          nutritional_value: {
            size: "на одну порцию",
            fats: 227.58,
            prots: 135.16,
            carbs: 82.54,
            kcal: 2919.08,
          },
          price: 1290,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d28",
          restaurant: 1,
          name: "Ребра свинные King Size с фисташками рибс",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "1077",
          nutritional_value: {
            size: "на одну порцию",
            fats: 188.81,
            prots: 103.81,
            carbs: 92.04,
            kcal: 2482.73,
          },
          price: 1290,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d29",
          restaurant: 1,
          name: "Ребра Dry Aged Medium Size говяжьи",
          category: {
            number: 5,
            name: "ребра",
          },
          weight: "451",
          nutritional_value: {
            size: "на одну порцию",
            fats: 96.17,
            prots: 68.14,
            carbs: 1.5,
            kcal: 1144.09,
          },
          price: 990,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d30",
          restaurant: 1,
          name: "Филе-миньон с зеленой спаржей",
          category: {
            number: 7,
            name: "стейки",
          },
          weight: "372",
          nutritional_value: {
            size: "на одну порцию",
            fats: 69.17,
            prots: 43.95,
            carbs: 16.81,
            kcal: 865.53,
          },
          price: 1090,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d31",
          restaurant: 1,
          name: "Фланк стейк с перечным соусом",
          category: {
            number: 7,
            name: "стейки",
          },
          weight: "274",
          nutritional_value: {
            size: "на одну порцию",
            fats: 30.02,
            prots: 45.35,
            carbs: 6.65,
            kcal: 478.18,
          },
          price: 790,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d32",
          restaurant: 1,
          name:
            "Френк стриплайн с коул-слоу, картофелем фри, кукурузой и соусом Jack Daniel's",
          category: {
            number: 7,
            name: "стейки",
          },
          weight: "858",
          nutritional_value: {
            size: "на одну порцию",
            fats: 90.31,
            prots: 91.42,
            carbs: 49.58,
            kcal: 1376.81,
          },
          price: 1490,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d33",
          restaurant: 1,
          name: "Куриная грудка с микс-салатом",
          category: {
            number: 8,
            name: "горячее",
          },
          weight: "331",
          nutritional_value: {
            size: "на одну порцию",
            fats: 9.7,
            prots: 49.75,
            carbs: 31.46,
            kcal: 412.13,
          },
          price: 420,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d34",
          restaurant: 1,
          name: "Классическая шаверма",
          category: {
            number: 9,
            name: "шаверма",
          },
          weight: "344",
          nutritional_value: {
            size: "на одну порцию",
            fats: 45.03,
            prots: 27.3,
            carbs: 59.79,
            kcal: 753.66,
          },
          price: 340,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d35",
          restaurant: 1,
          name: "Азиатская шаверма с креветками",
          category: {
            number: 9,
            name: "шаверма",
          },
          weight: "295",
          nutritional_value: {
            size: "на одну порцию",
            fats: 22.88,
            prots: 20.89,
            carbs: 87.87,
            kcal: 640.95,
          },
          price: 440,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d36",
          restaurant: 1,
          name: "Мексиканский буритто с мраморной говядиной",
          category: {
            number: 14,
            name: "буритто",
          },
          weight: "337",
          nutritional_value: {
            size: "на одну порцию",
            fats: 33.56,
            prots: 29.47,
            carbs: 79.41,
            kcal: 737.54,
          },
          price: 460,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d37",
          restaurant: 1,
          name: "Северная шаверма с олениной и брусникой",
          category: {
            number: 9,
            name: "шаверма",
          },
          weight: "356",
          nutritional_value: {
            size: "на одну порцию",
            fats: 58.67,
            prots: 21.17,
            carbs: 66.65,
            kcal: 879.27,
          },
          price: 490,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d38",
          restaurant: 1,
          name: "Фрэнкбургер с реберным мясом",
          category: {
            number: 10,
            name: "гамбургеры",
          },
          weight: "546,6",
          nutritional_value: {
            size: "на одну порцию",
            fats: 82.74,
            prots: 44.53,
            carbs: 42.64,
            kcal: 1093.32,
          },
          price: 520,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d39",
          restaurant: 1,
          name: "Хот-дог со сладкой горчицей и луком фри",
          category: {
            number: 15,
            name: "хот-доги",
          },
          weight: "201",
          nutritional_value: {
            size: "на одну порцию",
            fats: 41.55,
            prots: 14.39,
            carbs: 4.7,
            kcal: 450.31,
          },
          price: 390,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d40",
          restaurant: 1,
          name: "Чизбургер с мраморной говядиной",
          category: {
            number: 10,
            name: "гамбургеры",
          },
          weight: "285,4",
          nutritional_value: {
            size: "на одну порцию",
            fats: 25.53,
            prots: 17.31,
            carbs: 59.23,
            kcal: 535.95,
          },
          price: 540,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d41",
          restaurant: 1,
          name: "Сэндвич 4 сыра с ребрами",
          category: {
            number: 16,
            name: "сэндвичи",
          },
          weight: "327",
          nutritional_value: {
            size: "на одну порцию",
            fats: 84.9,
            prots: 49.05,
            carbs: 23.43,
            kcal: 1054.02,
          },
          price: 480,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d42",
          restaurant: 1,
          name: "Бургер с куриным филе и сыром чеддер",
          category: {
            number: 10,
            name: "гамбургеры",
          },
          weight: "515,4",
          nutritional_value: {
            size: "на одну порцию",
            fats: 39.53,
            prots: 63.43,
            carbs: 74.02,
            kcal: 905.55,
          },
          price: 470,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d43",
          restaurant: 1,
          name: "BBQ XL на компанию",
          category: {
            number: 8,
            name: "горячее",
          },
          weight: "1832",
          nutritional_value: {
            size: "на одну порцию",
            fats: 275.04,
            prots: 207.38,
            carbs: 115.38,
            kcal: 3766.37,
          },
          price: 2700,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d44",
          restaurant: 1,
          name: "Вафельные трубочки с вареной сгущенкой",
          category: {
            number: 11,
            name: "десерты",
          },
          weight: "247",
          nutritional_value: {
            size: "на одну порцию",
            fats: 40.83,
            prots: 26.77,
            carbs: 94.49,
            kcal: 852.56,
          },
          price: 290,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d45",
          restaurant: 1,
          name: "Классический чизкейк",
          category: {
            number: 11,
            name: "десерты",
          },
          weight: "41",
          nutritional_value: {
            size: "на одну порцию",
            fats: 0.72,
            prots: 1.58,
            carbs: 14.34,
            kcal: 70.13,
          },
          price: 320,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d46",
          restaurant: 1,
          name: "Шоколадный брауни со сливочным мороженым",
          category: {
            number: 11,
            name: "десерты",
          },
          weight: "232",
          nutritional_value: {
            size: "на одну порцию",
            fats: 56.86,
            prots: 14.99,
            carbs: 86.97,
            kcal: 919.57,
          },
          price: 340,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d47",
          restaurant: 1,
          name: "Мороженное",
          category: {
            number: 11,
            name: "десерты",
          },
          weight: "100",
          nutritional_value: {
            size: "на одну порцию",
            fats: 10,
            prots: 4,
            carbs: 28,
            kcal: 218,
          },
          price: 150,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d48",
          restaurant: 1,
          name: "Авокадо на гриле",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "102",
          nutritional_value: {
            size: "на одну порцию",
            fats: 19.59,
            prots: 1.94,
            carbs: 6.73,
            kcal: 211.01,
          },
          price: 250,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d49",
          restaurant: 1,
          name: "Битые огурцы",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "130",
          nutritional_value: {
            size: "на одну порцию",
            fats: 0.5,
            prots: 3.87,
            carbs: 9.11,
            kcal: 56.44,
          },
          price: 150,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d50",
          restaurant: 1,
          name: "Картофель фри",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "121",
          nutritional_value: {
            size: "на одну порцию",
            fats: 14.4,
            prots: 2.4,
            carbs: 7.2,
            kcal: 168,
          },
          price: 180,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d51",
          restaurant: 1,
          name: "Картофельное пюре с трюфельным маслом",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "142",
          nutritional_value: {
            size: "на одну порцию",
            fats: 33.38,
            prots: 3.28,
            carbs: 26.13,
            kcal: 418.06,
          },
          price: 220,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d52",
          restaurant: 1,
          name: "Красная фасоль в соусе тако",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "150",
          nutritional_value: {
            size: "на одну порцию",
            fats: 1.04,
            prots: 21.15,
            carbs: 54,
            kcal: 309.92,
          },
          price: 150,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d53",
          restaurant: 1,
          name: "Кукуруза гриль",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "405",
          nutritional_value: {
            size: "на одну порцию",
            fats: 29.42,
            prots: 15.14,
            carbs: 59.36,
            kcal: 566.78,
          },
          price: 220,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d54",
          restaurant: 1,
          name: "Овощи гриль",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "252",
          nutritional_value: {
            size: "на одну порцию",
            fats: 11.56,
            prots: 11.23,
            carbs: 14.6,
            kcal: 207.36,
          },
          price: 360,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d55",
          restaurant: 1,
          name: "Печеный картофель с розмарином",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "102",
          nutritional_value: {
            size: "на одну порцию",
            fats: 0.06,
            prots: 2.03,
            carbs: 20.2,
            kcal: 89.46,
          },
          price: 180,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d56",
          restaurant: 1,
          name: "Рис басмати",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "120",
          nutritional_value: {
            size: "на одну порцию",
            fats: 0.26,
            prots: 3.24,
            carbs: 37.2,
            kcal: 165.2,
          },
          price: 150,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d57",
          restaurant: 1,
          name: "Рис с овощами",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "330",
          nutritional_value: {
            size: "на одну порцию",
            fats: 0.44,
            prots: 3.95,
            carbs: 14.0,
            kcal: 75.71,
          },
          price: 220,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d58",
          restaurant: 1,
          name: "Хрустящая чиабатта",
          category: {
            number: 12,
            name: "гарниры",
          },
          weight: "90",
          nutritional_value: {
            size: "на одну порцию",
            fats: 2.7,
            prots: 7.2,
            carbs: 46.8,
            kcal: 240.3,
          },
          price: 80,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d59",
          restaurant: 1,
          name: "Английский завтрак",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "336",
          nutritional_value: {
            size: "на одну порцию",
            fats: 67.66,
            prots: 30.85,
            carbs: 50.1,
            kcal: 932.74,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d60",
          restaurant: 1,
          name: "Кальмары с соусом васаби и рисом басмати",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "360",
          nutritional_value: {
            size: "на одну порцию",
            fats: 37.15,
            prots: 45.99,
            carbs: 3.55,
            kcal: 532.32,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d61",
          restaurant: 1,
          name: "Каша 4 злака с семенами льна и отрубями",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "307",
          nutritional_value: {
            size: "на одну порцию",
            fats: 58.91,
            prots: 16.99,
            carbs: 23.61,
            kcal: 692.59,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d62",
          restaurant: 1,
          name: "Круассан классический",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "22",
          nutritional_value: {
            size: "на одну порцию",
            fats: 19.8,
            prots: 0,
            carbs: 0,
            kcal: 178.2,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d63",
          restaurant: 1,
          name: "Круассан с ветчиной и сыром",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "71",
          nutritional_value: {
            size: "на одну порцию",
            fats: 8.4,
            prots: 6.64,
            carbs: 0.85,
            kcal: 105.56,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d64",
          restaurant: 1,
          name: "Круассан с лососем и крем чиз",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "74",
          nutritional_value: {
            size: "на одну порцию",
            fats: 12.88,
            prots: 11.74,
            carbs: 0.45,
            kcal: 164.68,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d65",
          restaurant: 1,
          name: "Поджаренный тыквенный хлеб со стейком филе-миньон",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "296",
          nutritional_value: {
            size: "на одну порцию",
            fats: 28.8,
            prots: 18.9,
            carbs: 39.2,
            kcal: 491.6,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d66",
          restaurant: 1,
          name: "Рисовая каша на кокосовом молоке с манго",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "442",
          nutritional_value: {
            size: "на одну порцию",
            fats: 26.47,
            prots: 7.51,
            carbs: 58.91,
            kcal: 503.91,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d67",
          restaurant: 1,
          name: "Тост с лососем и авокадо",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "175",
          nutritional_value: {
            size: "на одну порцию",
            fats: 28.39,
            prots: 14.76,
            carbs: 28.91,
            kcal: 430.19,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
        {
          id: "1d68",
          restaurant: 1,
          name: "Тыквенные тосты с арахисовой пастой и нутеллой",
          category: {
            number: 13,
            name: "завтраки",
          },
          weight: "180",
          nutritional_value: {
            size: "на одну порцию",
            fats: 29.3,
            prots: 7.3,
            carbs: 61.5,
            kcal: 538.9,
          },
          price: null,
          composition: null,
          inBasket: false,
          isFavorite: false,
        },
      ],
    },
  ];
}

export default foodData;
